routes/web.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\ServerMonitor;
use App\Notifications\DoneVoting;
use App\Student;
use App\Traits\SystemInfo;
use App\User;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;

Route::redirect('/','/vote/login');

/*
 *  For System Administrator Auth Path
 */
Route::get('/sysadmin/', 'sysadmin\auth\login@index')->name('sysadmin.login.page');
Route::post('/sysadmin/login','sysadmin\auth\login@logmein')->name('sysadmin.login');
Route::get('/sysadmin/login/success','sysadmin\auth\login@successlogin');
Route::post('/sysadmin/logout','sysadmin\auth\login@logout')->name('sysadmin.logout');

Route::get('/test', function () {
    $user = User::all();
    $student = Student::all();
    //ddd($student[0]);
    Notification::send($user, new DoneVoting($student[0]));
    return 'Event Fired';
});


/*
 *  sysadmin Dashboard
 */
Route::namespace('sysadmin')->prefix('sysadmin')->name('sysadmin.')->middleware(['auth'])->group(function () {
    // System Admin and Developer Admin Dashboard
    Route::get('dashboard', 'Dashboard@index')->name('dashboards');
    // Voters / Student Register & info
    Route::resource('voters', 'voters\voters');
    // Generate Random Password
    Route::get('voters/{id}/generate/random/password', 'voters\voters@GeneratePassword')->name('generateRndPassword');
    // Candidates
    Route::resource('candidates', 'candidates\CandidatesController');
    //users
    Route::resource('account/user', 'account\AccountUserController');
    // Profile
    Route::resource('account/profile', 'profile\Profile');
    //user Activate & Deactivate
    Route::post('account/user/{id}/deactivate', 'account\AccountUserController@Deactivate')->name('user.deactivate');
    Route::post('account/user/{id}/activate', 'account\AccountUserController@Activate')->name('user.activate');
    // Organization
    Route::resource('organization', 'candidates\Organization');
    // General Settings
    Route::resource('settings/general','settings\General');
    // Seats
    Route::get('settings/seats/configuration','settings\SeatsController@index')->name('seats.index');
    Route::put('settings/seats/configuration','settings\SeatsController@update')->name('seats.update');
    // Database Setting
    Route::get('settings/database', 'settings\Database@index')->name('database.page');
    Route::get('settings/database/table/{table}/truncate', 'settings\Database@truncate')->name('database.truncate');
    // Bulk Import Path
    Route::post('voters/bulk/import','voters\voters@import')->name('VotersImport');
    Route::get('voters/bulk/import/file/format','voters\voters@downloadfile')->name('VotersFileFormatImport');

   /*
    *  AJAX Path URL REQUEST
    *
    */
    // system information path
    Route::get('/server/info','sysinfo\info@sysinfo')->name('sysinfopath');

});



/*
 *  For Student Voting Auth Path
 */
Route::get('/vote/login', 'voters\auth\login@index')->name('voters.login.page');
Route::post('/vote/login','voters\auth\login@checklogin')->name('voters.login');
Route::get('/vote/login/success', 'voters\auth\login@successlogin');
Route::post('/vote/logout','voters\auth\login@logout')->name('voters.logout');

/*
 *  Route for student voting dashboard
 * This need to have a auth
 */

Route::namespace('voters')->prefix('precinct')->name('voters.')->middleware(['precinct.door','precinct.voters'])->group(function (){
    Route::get('vote/candidates','vote\CandidatesController@index')->name('dashboards');


    // Semantic API
    Route::post('vote/precinct/candidates', 'vote\VoteController@upVote')->name('voters.vote');

});

Route::view('/vote/close/countdown','partials.vote-is-closed-countdown')->name('countdown.page')->middleware(['precinct.door']);

app/Http/Controllers/sysadmin/voters/voters.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

namespace App\Http\Controllers\sysadmin\voters;

use App\Imports\VotersImport;
use App\Student;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Facades\Excel;

class voters extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        return view('AdminPanel.voters.voters-list')
            ->with('students', Student::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return  view('AdminPanel.voters.Register');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $this->validate($request, [
            'School_Id' => 'required|unique:students,Student_ID',
            'First_Name' => 'required',
            'Last_Name' => 'required',
            'Middle_Name' => 'required',
            'Grade_Level' => 'required',

        ]);

        Student::create([
            'Student_ID' => $request->input('School_Id'),
            'FirstName' => $request->input('First_Name'),
            'LastName' => $request->input('Last_Name'),
            'MiddleName' => $request->input('Middle_Name'),
            'GradeLvl' => $request->input('Grade_Level')
        ]);

        session()->flash('alert-success', 'New voters successfully created.');
        return  redirect()->route('sysadmin.voters.create');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // return the data to the ajax { json response }
        $data = Student::find($id);
        $res = array(
                'Status' => 'passed',
                'Success' => true,
                'result' => $data,
        );
        return response()->json($res);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $user = Student::find($id);
        $user->update([
            'FirstName' => $request->input('First_Name'),
            'LastName' => $request->input('Last_Name'),
            'MiddleName' => $request->input('Middle_Name'),
            'GradeLvl' => $request->input('Grade_Level')
        ]);

        session()->flash('alert-success', 'Voters / Student #'.$user->Student_ID.' has been updated!');
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $user = Student::find($id);

        if(!$user->isActive) {
            $res = Student::where('id', $id)->delete();
            if($res){
                session()->flash('alert-success', 'Voters / Student #'.$user->Student_ID.' has already been deleted!');
                return back();
            }else{
                session()->flash('alert-success', 'Make sure the Current User #'.$user->Student_ID.' is existing in the database.');
                return back();
            }

        }else{
            session()->flash('alert-success', 'Unable to delete voters / student that is online.');
            return back();
        }

    }

    public function GeneratePassword($id)
    {
        //
        $user = Student::find($id);
        $pass = Str::random(6);
        $user->password = bcrypt($pass);
        $user->save();

        return response()->json([
            'pass' => $pass,
        ]);
    }

    public  function  import(Request $request)
    {
        //
        $this->validate($request,[
            'import_file' => 'mimetypes:text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel|required'
        ]);

        $bulkdata = Excel::toCollection(new VotersImport(), $request->file('import_file'));

        foreach($bulkdata as $voter )
        {
            foreach($voter as $data){
                Student::updateOrCreate([
                    'Student_ID' => $data['school_id']
                ],
                    [
                        'FirstName' => $data['first_name'],
                        'LastName' => $data['last_name'],
                        'MiddleName' => $data['middle_name'],
                        'GradeLvl' => $data['grade_level'],

                    ]);
            }
        }
        session()->flash('alert-success', 'Bulk import successfully save and update for the duplicates.');
        return redirect()->route('sysadmin.voters.index');
    }

    public function downloadfile(){
        //return Storage::download('students_201909180945.xlsx',)
        return Storage::disk('public')->download('storage/files/students_201909180945.xlsx','voters-student_201909180945.xlsx', ['Content-Description' =>  'File Transfer','Content-Type' => 'application/octet-stream','Content-Disposition' => 'attachment; filename=voters-student_201909180945.xlsx']);
    }
}

app/Http/Controllers/voters/vote/CandidatesController.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

namespace App\Http\Controllers\voters\vote;

use App\Candidates;
use App\Http\Controllers\Controller;

class CandidatesController extends Controller
{
    public function index()
    {
        //
        $president = Candidates::with('organizations')->where('Position', 'president')->get();
        $vpresident = Candidates::where('Position', 'vice-president')->get();
        $secretary = Candidates::where('Position', 'secretary')->get();
        $treasurer = Candidates::where('Position', 'treasurer')->get();
        $auditor = Candidates::where('Position', 'auditor')->get();
        $pio = Candidates::where('Position', 'pio')->get();
        $business_manager = Candidates::where('Position', 'business-manager')->get();
        $senior_representative = Candidates::where('Position', 'senior-representative')->get();
        $junior_representative = Candidates::where('Position', 'junior-representative')->get();


        return view('voters.vote-dashboard')
           /* ->with([
                'presidents' => $president,
                'vpresidents' => $vpresident,
                'secretarys' => $secretary,
                'treasurers' => $treasurer,
                'auditors' => $auditor,
                'pios' => $pio,
                'business_managers' => $business_manager,
                'seniors' => $senior_representative,
                'juniors' => $junior_representative
            ]);*/
           ->with(
               'presidents', $president
           );


    }
}

resources/views/AdminPanel/voters/Register.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Register New Voters</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            {{-- Added Validation Error here--}}
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            {{-- /. End of Validation Error here--}}
                            <br />
                            <form method="post" action="{{ route('sysadmin.voters.store') }}"  data-parsley-validate class="form-horizontal form-label-left" >
                                @csrf
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="SchoolID">School ID No. <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="SchoolID" required="required" class="form-control col-md-7 col-xs-12" name="School_Id" value="{{ old('schoolid') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">First Name <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="First_Name" value="{{ old('firstname') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Last Name <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input type="text" id="last-name" name="Last_Name" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('lastname') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name / Initial <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="middle-name" class="form-control col-md-7 col-xs-12" required="required" type="text" name="Middle_Name" value="{{ old('middlename') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="gradelvl" class="control-label col-md-3 col-sm-3 col-xs-12">Grade Level <span class="required">*</span>
                                    </label>
                                    <div class="col-md-6 col-sm-6 col-xs-12">
                                        <input id="gradelvl" class="form-control col-md-7 col-xs-12" type="text" name="Grade_Level" required="required" value="{{ old('gradelvl') }}">
                                    </div>
                                </div>
                                <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                        <button class="btn btn-primary" type="reset">Reset</button>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
@endsection

resources/views/AdminPanel/voters/voters-list.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')
     <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="clearfix"></div>
            <!-- Validation Data Response error-->
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- Validation Data Response error-->

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>List of Voters / Student</h2>
                            <ul class="nav navbar-right panel_toolbox">
                               {{-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>--}}
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-user-plus fa-2x"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="{{ url(route('sysadmin.voters.create')) }}"><i class="fa fa-user-plus"></i> Add Voters</a>
                                        </li>
                                        <li>
                                            <a href="#" data-toggle="modal" data-target=".importuser"><i class="fa fa-upload"></i> Bulk upload Voters / Students</a>
                                        </li>
                                        <li>
                                            <a href="{{ route('sysadmin.VotersFileFormatImport') }}"><i class="fa fa-download"></i> Download Bulk file format</a>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card-box ">
                                        <table id="" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                                            <thead>
                                            <tr>
                                                {{--<th><input type="checkbox" id="checkall" class="flat"> Select All</th>--}}
                                                <th>School ID</th>
                                                <th>First Name</th>
                                                <th>Last Name</th>
                                                <th>Middle Name</th>
                                                <th>Grade Level</th>
                                                <th>Done Voting?</th>
                                                <th>is Active?</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($students as $student)
                                                <tr>
                                                   {{-- <td><input type="checkbox" class="flat chck"></td>--}}
                                                    <td>{{ $student->Student_ID }}</td>
                                                    <td>{{ $student->FirstName }}</td>
                                                    <td>{{ $student->LastName }}</td>
                                                    <td>{{ $student->MiddleName }}</td>
                                                    <td>{{ $student->GradeLvl }}</td>
                                                    <td>
                                                        @if($student->doneVoting === 1)
                                                            Yes
                                                        @else
                                                            No
                                                        @endif
                                                    </td>
                                                    <td>
                                                        @if($student->isActive === 1)
                                                            Yes
                                                        @else
                                                            No
                                                        @endif
                                                    </td>
                                                    <td>
                                                        <button type="button" class="btn btn-info btn-round" onclick="GenPassword({{ $student->id }})" data-toggle="tooltip" title="Generate Password"><i class="fa fa-refresh"></i></button>
                                                        <button type="button" class="btn btn-primary btn-round"  data-toggle="modal" data-target="#edituser-modal" data-middlename="{{ $student->MiddleName }}" data-gradelvl="{{ $student->GradeLvl }}" data-lastname="{{ $student->LastName }}" data-firstname="{{ $student->FirstName }}" data-studentid="{{ $student->Student_ID }}" data-id="{{ $student->id }}" data-route="{{ route('sysadmin.voters.update', $student->id) }}" ><i class="fa fa-edit" data-toggle="tooltip" title="Edit Voter / Student"></i></button>
                                                        <button type="button" class="btn btn-danger btn-round" onclick="deleteVoter( {{ $student->Student_ID }})" data-toggle="tooltip" title="Delete Voter / Student"><i class="fa fa-trash-o"></i></button>
                                                        <form action="{{ route('sysadmin.voters.destroy', $student->id) }}" method="POST" id="{{ $student->Student_ID }}">
                                                            {{ method_field('DELETE') }}
                                                            @csrf
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Import -->
    @include('AdminPanel.voters.modals.importUser')
     @include('AdminPanel.voters.modals.editvoters')
    <!-- /.Modal Import -->

    <!-- /page content -->
<script>
       $('#edituser-modal').on('show.bs.modal', function(e){

           const route = $(e.relatedTarget).data('route');

           // adding the value to the form
           $('#uid').val($(e.relatedTarget).data('id'));
           $('#first-name').val($(e.relatedTarget).data('firstname'));
           $('#last-name').val($(e.relatedTarget).data('lastname'));
           $('#middle-name').val($(e.relatedTarget).data('middlename'));
           $('#gradelvl').val($(e.relatedTarget).data('gradelvl'));
           //attached a dynamic URL action to the form
           $('#edituserForm').attr('action', route);

       });
   function GenPassword(id) {
            //using SweetAlert
       const uid = id;
       const route = "{{ route('sysadmin.generateRndPassword', $student->id) }}";
       const swalWithBootstrapButtons = Swal.mixin({
           customClass: {
               confirmButton: 'btn btn-success btn-round btn-lg',
               cancelButton: 'btn btn-danger btn-round btn-lg'
           },
           buttonsStyling: false
       });
       swalWithBootstrapButtons.fire({
           title: 'Are you sure?',
           text: "Generate Random Password for this Student / Voter",
           type: 'question',
           allowEscapeKey: false,
           allowOutsideClick: false,
           showCancelButton: true,
           confirmButtonText: 'Yes, Generate new password',
           cancelButtonText: 'No, Cancel!',
           showLoaderOnConfirm: true,
           reverseButtons: true,
       }).then((result) => {
           if (result.value) {
               //delete that ***
                $.ajax({
                    type: "GET",
                    url: route,
                    success:function (event) {
                        Swal.fire(
                            'New Password:',
                            event['pass'],
                            'success'
                        )
                    }
                });
           }

       })
       }
   function deleteVoter(id){
       const uid = id;
       const swalWithBootstrapButtons = Swal.mixin({
           customClass: {
               confirmButton: 'btn btn-success btn-round btn-lg',
               cancelButton: 'btn btn-danger btn-round btn-lg'
           },
           buttonsStyling: false
       });
       swalWithBootstrapButtons.fire({
           title: 'Are you sure?',
           text: "You won't be able to revert this!",
           type: 'warning',
           allowEscapeKey: false,
           allowOutsideClick: false,
           showCancelButton: true,
           confirmButtonText: 'Yes, delete it!',
           cancelButtonText: 'No, cancel!',
           reverseButtons: true,
       }).then((result) => {
           if (result.value) {
               //delete that ***
               $("#"+id).submit();
           }

       })
   }

   $(document).ready(function(){

       $(".keytable").DataTable({
           responsive: true,
           keys: !0,
           dom: "Bfrtip",
           buttons: [{
               extend: "copyHtml5",
               className: "btn-sm btn-round"
           }, {
               extend: "csvHtml5",
               className: "btn-sm btn-round"
           }, {
               extend: "print",
               className: "btn-sm btn-round"
           }],
       });
       $('[data-toggle="tooltip"]').tooltip();
   });
</script>

@endsection