routes/web.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\ServerMonitor;
use App\Notifications\DoneVoting;
use App\Student;
use App\Traits\SystemInfo;
use App\User;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;

Route::redirect('/','/vote/login');

/*
 *  For System Administrator Auth Path
 */
Route::get('/sysadmin/', 'sysadmin\auth\login@index')->name('sysadmin.login.page');
Route::post('/sysadmin/login','sysadmin\auth\login@logmein')->name('sysadmin.login');
Route::get('/sysadmin/login/success','sysadmin\auth\login@successlogin');
Route::post('/sysadmin/logout','sysadmin\auth\login@logout')->name('sysadmin.logout');

Route::get('/test', function () {
    $user = User::all();
    $student = Student::all();
    //ddd($student[0]);
    Notification::send($user, new DoneVoting($student[0]));
    return 'Event Fired';
});


/*
 *  sysadmin Dashboard
 */
Route::namespace('sysadmin')->prefix('sysadmin')->name('sysadmin.')->middleware(['auth'])->group(function () {
    // System Admin and Developer Admin Dashboard
    Route::get('dashboard', 'Dashboard@index')->name('dashboards');
    // Voters / Student Register & info
    Route::resource('voters', 'voters\voters');
    // Generate Random Password
    Route::get('voters/{id}/generate/random/password', 'voters\voters@GeneratePassword')->name('generateRndPassword');
    // Candidates
    Route::resource('candidates', 'candidates\CandidatesController');
    //users
    Route::resource('account/user', 'account\AccountUserController');
    // Profile
    Route::resource('account/profile', 'profile\Profile');
    //user Activate & Deactivate
    Route::post('account/user/{id}/deactivate', 'account\AccountUserController@Deactivate')->name('user.deactivate');
    Route::post('account/user/{id}/activate', 'account\AccountUserController@Activate')->name('user.activate');
    // Organization
    Route::resource('organization', 'candidates\Organization');
    // General Settings
    Route::resource('settings/general','settings\General');
    // Seats
    Route::get('settings/seats/configuration','settings\SeatsController@index')->name('seats.index');
    Route::put('settings/seats/configuration','settings\SeatsController@update')->name('seats.update');
    // Database Setting
    Route::get('settings/database', 'settings\Database@index')->name('database.page');
    Route::get('settings/database/table/{table}/truncate', 'settings\Database@truncate')->name('database.truncate');
    // Bulk Import Path
    Route::post('voters/bulk/import','voters\voters@import')->name('VotersImport');
    Route::get('voters/bulk/import/file/format','voters\voters@downloadfile')->name('VotersFileFormatImport');

   /*
    *  AJAX Path URL REQUEST
    *
    */
    // system information path
    Route::get('/server/info','sysinfo\info@sysinfo')->name('sysinfopath');

});



/*
 *  For Student Voting Auth Path
 */
Route::get('/vote/login', 'voters\auth\login@index')->name('voters.login.page');
Route::post('/vote/login','voters\auth\login@checklogin')->name('voters.login');
Route::get('/vote/login/success', 'voters\auth\login@successlogin');
Route::post('/vote/logout','voters\auth\login@logout')->name('voters.logout');

/*
 *  Route for student voting dashboard
 * This need to have a auth
 */

Route::namespace('voters')->prefix('precinct')->name('voters.')->middleware(['precinct.door','precinct.voters'])->group(function (){
    Route::get('vote/candidates','vote\CandidatesController@index')->name('dashboards');


    // Semantic API
    Route::post('vote/precinct/candidates', 'vote\VoteController@upVote')->name('voters.vote');

});

Route::view('/vote/close/countdown','partials.vote-is-closed-countdown')->name('countdown.page')->middleware(['precinct.door']);

app/Organization.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2019.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

namespace App;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Auditable;

class Organization extends Model implements Auditable
{
    use \OwenIt\Auditing\Auditable;
    //
    protected $auditInclude = [
        'Organization_name', 'Organization_description',
    ];

    protected $fillable = [
      'Organization_name' ,
        'Organization_description'
    ];

    public function candidates(){
        return $this->belongsToMany(Candidates::class);
    }
}

app/Http/Controllers/sysadmin/candidates/Organization.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2019.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

namespace App\Http\Controllers\sysadmin\candidates;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Organization as OrgModel;

class Organization extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $orgmodel = OrgModel::all();
        return view('AdminPanel.organization.org-list')
            ->with('orgdb', $orgmodel);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('AdminPanel.organization.add-organization');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function store(Request $request)
    {
        //

        $this->validate($request, [
           'orgname' => 'required|unique:organizations,Organization_name',
            'orgdescription' => 'required'
        ]);

        OrgModel::create([
           'Organization_name' => $request->input('orgname'),
           'Organization_description' => $request->input('orgdescription')
        ]);

        session()->flash('alert-success', 'New Organization has been added!');
        return  redirect()->route('sysadmin.organization.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, $id)
    {
        //
        $this->validate($request, [
            'orgname' => 'required|unique:organizations,Organization_name',
            'orgdescription' => 'required'
        ]);

        $orgdata = OrgModel::find($id);
        $orgdata->update([
            'Organization_name' => $request->input('orgname'),
            'Organization_description' => $request->input('orgdescription')
        ]);

        session()->flash('alert-success', 'Organization has successfully updated!');
        return  redirect()->route('sysadmin.organization.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        OrgModel::find($id)->delete();

        session()->flash('alert-success', 'Organization has successfully deleted!');
        return  redirect()->route('sysadmin.organization.index');
    }
}

resources/views/AdminPanel/organization/add-organization.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        {{-- Added Validation Error here--}}
        @include('partials.validation-message')
        {{-- /. End of Validation Error here--}}

        <div class="">
            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Create new Organization</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            <br />
                            <form class="form" id="regOrg"  action="{{ route('sysadmin.organization.store') }}" method="post"  data-parsley-validate class="form-horizontal form-label-left">
                                @csrf
                                <!-- Date will be open date and time -->
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="orgname">Organization / Club name<span class="required">*</span>
                                    </label>
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <input type="text" id="orgname" required="required" class="form-control col-md-7 col-xs-12" name="orgname" value="{{ old('orgname') }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label col-md-3 col-sm-3 col-xs-12" for="orgdesc">Organization Description<span class="required">*</span>
                                    </label>
                                    <div class="col-md-12 col-sm-12 col-xs-12">
                                        <input type="text" id="orgdesc" required="required" class="form-control col-md-7 col-xs-12" name="orgdescription" value="{{ old('orgdescription') }}">
                                    </div>
                                </div>

                                    <div class="ln_solid"></div>
                                <div class="form-group">
                                    <div class="col-md-6 col-sm-6 col-xs-12" style="margin-top: 10px;">
                                        <button class="btn btn-primary" type="reset">Reset</button>
                                        <button type="submit" class="btn btn-success">Submit</button>
                                    </div>
                                </div>

                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
    <script>

    </script>

@endsection

resources/views/AdminPanel/organization/org-list.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="clearfix"></div>
            <!-- Validation Data Response error-->
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- Validation Data Response error-->

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>List of Organization</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                {{-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                 </li>--}}
                                <a href="{{ url(route('sysadmin.organization.create')) }}"><i class="fa fa-user-plus fa-2x"></i></a>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card-box ">
                                        <table id="" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                                            <thead>
                                            <tr>
                                                {{--<th><input type="checkbox" id="checkall" class="flat"> Select All</th>--}}
                                                <th>Organization Name</th>
                                                <th>Description</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($orgdb as $orgdata)
                                                <tr>
                                                    {{-- <td><input type="checkbox" class="flat chck"></td>--}}
                                                    <td>{{ $orgdata->Organization_name }}</td>
                                                    <td>{{ $orgdata->Organization_description }}</td>
                                                    <td>
                                                        <button type="button" class="btn btn-primary btn-round"  data-toggle="modal" data-target="#edit-modal" data-orgname="{{ $orgdata->Organization_name }}" data-orgdescription="{{ $orgdata->Organization_description }}" data-route="{{ route('sysadmin.organization.update', $orgdata->id) }}" ><i class="fa fa-edit" data-toggle="tooltip" title="Edit Organization"></i></button>
                                                        <button type="button" class="btn btn-danger btn-round" onclick="deleteData( {{ $orgdata->id }})" data-toggle="tooltip" title="Delete Organization"><i class="fa fa-trash-o"></i></button>
                                                        <form action="{{ route('sysadmin.organization.destroy', $orgdata->id) }}" method="POST" id="{{ $orgdata->id }}">
                                                            {{ method_field('DELETE') }}
                                                            @csrf
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Modal Import -->
    @include('AdminPanel.organization.modal.edit-org')
    <!-- /.Modal Import -->

    <!-- /page content -->
    <script>
        $('#edit-modal').on('show.bs.modal', function(e){

            const route = $(e.relatedTarget).data('route');

            // adding the value to the form
            $('#orgname').val($(e.relatedTarget).data('orgname'));
            $('#orgdesc').val($(e.relatedTarget).data('orgdescription'));
            //attached a dynamic URL action to the form
            $('#editForm').attr('action', route);

        });

        function deleteData(id){
            const uid = id;
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success btn-round btn-lg',
                    cancelButton: 'btn btn-danger btn-round btn-lg'
                },
                buttonsStyling: false
            });
            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                allowEscapeKey: false,
                allowOutsideClick: false,
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
            }).then((result) => {
                if (result.value) {
                    //delete that ***
                    $("#"+id).submit();
                }

            })
        }

        $(document).ready(function(){

            $(".keytable").DataTable({
                responsive: true,
                keys: !0,
                dom: "Bfrtip",
                buttons: [{
                    extend: "copyHtml5",
                    className: "btn-sm btn-round"
                }, {
                    extend: "csvHtml5",
                    className: "btn-sm btn-round"
                }, {
                    extend: "print",
                    className: "btn-sm btn-round"
                }],
            });
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

@endsection