routes/web.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\ServerMonitor;
use App\Notifications\DoneVoting;
use App\Student;
use App\Traits\SystemInfo;
use App\User;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;

Route::redirect('/','/vote/login');

/*
 *  For System Administrator Auth Path
 */
Route::get('/sysadmin/', 'sysadmin\auth\login@index')->name('sysadmin.login.page');
Route::post('/sysadmin/login','sysadmin\auth\login@logmein')->name('sysadmin.login');
Route::get('/sysadmin/login/success','sysadmin\auth\login@successlogin');
Route::post('/sysadmin/logout','sysadmin\auth\login@logout')->name('sysadmin.logout');

Route::get('/test', function () {
    $user = User::all();
    $student = Student::all();
    //ddd($student[0]);
    Notification::send($user, new DoneVoting($student[0]));
    return 'Event Fired';
});


/*
 *  sysadmin Dashboard
 */
Route::namespace('sysadmin')->prefix('sysadmin')->name('sysadmin.')->middleware(['auth'])->group(function () {
    // System Admin and Developer Admin Dashboard
    Route::get('dashboard', 'Dashboard@index')->name('dashboards');
    // Voters / Student Register & info
    Route::resource('voters', 'voters\voters');
    // Generate Random Password
    Route::get('voters/{id}/generate/random/password', 'voters\voters@GeneratePassword')->name('generateRndPassword');
    // Candidates
    Route::resource('candidates', 'candidates\CandidatesController');
    //users
    Route::resource('account/user', 'account\AccountUserController');
    // Profile
    Route::resource('account/profile', 'profile\Profile');
    //user Activate & Deactivate
    Route::post('account/user/{id}/deactivate', 'account\AccountUserController@Deactivate')->name('user.deactivate');
    Route::post('account/user/{id}/activate', 'account\AccountUserController@Activate')->name('user.activate');
    // Organization
    Route::resource('organization', 'candidates\Organization');
    // General Settings
    Route::resource('settings/general','settings\General');
    // Seats
    Route::get('settings/seats/configuration','settings\SeatsController@index')->name('seats.index');
    Route::put('settings/seats/configuration','settings\SeatsController@update')->name('seats.update');
    // Database Setting
    Route::get('settings/database', 'settings\Database@index')->name('database.page');
    Route::get('settings/database/table/{table}/truncate', 'settings\Database@truncate')->name('database.truncate');
    // Bulk Import Path
    Route::post('voters/bulk/import','voters\voters@import')->name('VotersImport');
    Route::get('voters/bulk/import/file/format','voters\voters@downloadfile')->name('VotersFileFormatImport');

   /*
    *  AJAX Path URL REQUEST
    *
    */
    // system information path
    Route::get('/server/info','sysinfo\info@sysinfo')->name('sysinfopath');

});



/*
 *  For Student Voting Auth Path
 */
Route::get('/vote/login', 'voters\auth\login@index')->name('voters.login.page');
Route::post('/vote/login','voters\auth\login@checklogin')->name('voters.login');
Route::get('/vote/login/success', 'voters\auth\login@successlogin');
Route::post('/vote/logout','voters\auth\login@logout')->name('voters.logout');

/*
 *  Route for student voting dashboard
 * This need to have a auth
 */

Route::namespace('voters')->prefix('precinct')->name('voters.')->middleware(['precinct.door','precinct.voters'])->group(function (){
    Route::get('vote/candidates','vote\CandidatesController@index')->name('dashboards');


    // Semantic API
    Route::post('vote/precinct/candidates', 'vote\VoteController@upVote')->name('voters.vote');

});

Route::view('/vote/close/countdown','partials.vote-is-closed-countdown')->name('countdown.page')->middleware(['precinct.door']);

resources/views/AdminPanel/templates/footer.blade.php
<!-- footer content -->
<footer class="footer_fixed">
    <div class="pull-right">
        <i class="fa fa-paw fa-2x"></i> eVote System - All right reserved &copy; 2019 &dash; MarJose Darang
    </div>
    <div class="clearfix"></div>
</footer>
<!-- /footer content -->

resources/views/AdminPanel/templates/master_template.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title> @yield('title') </title>

    {{--
    |
    | ------------------------------------------------------------------------------------------
    | All CSS Libraries
    | ----------------------------------------------------------------------------------------
    |
    |--}}

    <!-- Bootstrap -->
    <link href=" {{ asset('gentelella-1.4.0/vendors/bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{ asset('gentelella-1.4.0/vendors/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{ asset('gentelella-1.4.0/vendors/nprogress/nprogress.css') }}" rel="stylesheet">
    <!-- iCheck -->
    <link href="{{ asset('gentelella-1.4.0/vendors/iCheck/skins/flat/green.css') }}" rel="stylesheet">
    <!-- bootstrap-wysiwyg -->
    <link href="{{ asset('gentelella-1.4.0/vendors/google-code-prettify/bin/prettify.min.css') }}" rel="stylesheet">
    <!-- Select2 -->
    <link href="{{ asset('gentelella-1.4.0/vendors/select2/dist/css/select2.min.css') }}" rel="stylesheet">
    <!-- Switchery -->
    <link href="{{ asset('gentelella-1.4.0/vendors/switchery/dist/switchery.min.css') }}" rel="stylesheet">
    <!-- starrr -->
    <link href="{{ asset('gentelella-1.4.0/vendors/starrr/dist/starrr.css') }}" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{{ asset('gentelella-1.4.0/vendors/bootstrap-daterangepicker/daterangepicker.css') }}" rel="stylesheet">
    <!-- Ion.RangeSlider -->
    <link href="{{ asset('gentelella-1.4.0/vendors/normalize-css/normalize.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/ion.rangeSlider/css/ion.rangeSlider.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/ion.rangeSlider/css/ion.rangeSlider.skinFlat.css') }}" rel="stylesheet">
    <!-- Bootstrap Colorpicker -->
    <link href="{{ asset('gentelella-1.4.0/vendors/mjolnic-bootstrap-colorpicker/dist/css/bootstrap-colorpicker.min.css') }}" rel="stylesheet">
    <!-- Datatables -->
    <link href="{{ asset('gentelella-1.4.0/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('gentelella-1.4.0/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css') }}" rel="stylesheet">
    <!-- SweetAlert2 -->
    <link href="{{ asset('sweetalert2/@sweetalert2/themes/dark/dark.css') }}" rel="stylesheet">

    <!-- FileInput -->
    <link href="{{ asset('bootstrap-fileinput-4/css/fileinput.css') }}" rel="stylesheet">
    <link href="{{ asset('bootstrap-fileinput-4/css/fileinput-rtl.css') }}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{ asset('gentelella-1.4.0/build/css/custom.min.css') }}" rel="stylesheet">



    {{--
    |
    | ------------------------------------------------------------------------------------------------------
    | All Javascript Libraries
    | -----------------------------------------------------------------------------------------------------
    |
    --}}
    <script defer src="{{ mix('js/app.js') }}"></script>
    <!-- jQuery -->
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery/dist/jquery.js') }}"></script>
    <!-- Bootstrap -->
    <script src="{{ asset('gentelella-1.4.0/vendors/bootstrap/dist/js/bootstrap.js') }}"></script>
    {{-- Smart resize--}}
    <script src="{{ asset('gentelella-1.4.0/src/js/helpers/smartresize.js') }}"></script>
    <!-- FastClick -->
    <script src="{{ asset('gentelella-1.4.0/vendors/fastclick/lib/fastclick.js') }}"></script>
    <!-- NProgress -->
    <script src="{{ asset('gentelella-1.4.0/vendors/nprogress/nprogress.js') }}"></script>
    <!-- bootstrap-progressbar -->
    <script src="{{ asset('gentelella-1.4.0/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
    <!-- iCheck -->
    <script src="{{ asset('gentelella-1.4.0/vendors/iCheck/icheck.min.js') }}"></script>
    <!-- bootstrap-wysiwyg -->
    <script src="{{ asset('gentelella-1.4.0/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery.hotkeys/jquery.hotkeys.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/google-code-prettify/src/prettify.js') }}"></script>
    <!-- jQuery Tags Input -->
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery.tagsinput/src/jquery.tagsinput.js') }}"></script>
    <!-- Switchery -->
    <script src="{{ asset('gentelella-1.4.0/vendors/switchery/dist/switchery.min.js') }}"></script>
    <!-- Select2 -->
    <script src="{{ asset('gentelella-1.4.0/vendors/select2/dist/js/select2.full.min.js') }}"></script>
    <!-- Parsley -->
    <script src="{{ asset('gentelella-1.4.0/vendors/parsleyjs/dist/parsley.min.js') }}"></script>
    <!-- Autosize -->
    <script src="{{ asset('gentelella-1.4.0/vendors/autosize/dist/autosize.min.js') }}"></script>
    <!-- jQuery autocomplete -->
    <script src="{{ asset('gentelella-1.4.0/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js') }}"></script>
    <!-- starrr -->
    <script src="{{ asset('gentelella-1.4.0/vendors/starrr/dist/starrr.js') }}"></script>
    <!-- Chart.js -->
    <script src="{{ asset('gentelella-1.4.0/vendors/Chart.js/dist/Chart.min.js') }}"></script>
    <!-- jQuery Sparklines -->
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
    <!-- Flot -->
    <script src="{{ asset('gentelella-1.4.0/vendors/Flot/jquery.flot.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/Flot/jquery.flot.pie.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/Flot/jquery.flot.time.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/Flot/jquery.flot.stack.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/Flot/jquery.flot.resize.js') }}"></script>
    <!-- Flot plugins -->
    <script src="{{ asset('gentelella-1.4.0/vendors/flot.orderbars/js/jquery.flot.orderBars.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/flot-spline/js/jquery.flot.spline.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/flot.curvedlines/curvedLines.js') }}"></script>
    <!-- DateJS -->
    <script src="{{ asset('gentelella-1.4.0/vendors/DateJS/build/date.js') }}"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="{{ asset('gentelella-1.4.0/vendors/moment/min/moment.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/bootstrap-daterangepicker/daterangepicker.js') }}"></script>
    <!-- Datatables -->
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-keytable/js/dataTables.keyTable.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-responsive/js/dataTables.responsive.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/datatables.net-scroller/js/dataTables.scroller.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/jszip/dist/jszip.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/pdfmake/build/pdfmake.min.js') }}"></script>
    <script src="{{ asset('gentelella-1.4.0/vendors/pdfmake/build/vfs_fonts.js') }}"></script>
    <!-- Ion.RangeSlider -->
    <script src="{{ asset('gentelella-1.4.0/vendors/ion.rangeSlider/js/ion.rangeSlider.min.js') }}"></script>
    <!-- Bootstrap Colorpicker -->
    <script src="{{ asset('gentelella-1.4.0/vendors/mjolnic-bootstrap-colorpicker/dist/js/bootstrap-colorpicker.min.js') }}"></script>
    <!-- jquery.inputmask -->
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
    <!-- jQuery Knob -->
    <script src="{{ asset('gentelella-1.4.0/vendors/jquery-knob/dist/jquery.knob.min.js') }}"></script>
    <!-- SweetAlert2 -->
    <script src="{{ asset('sweetalert2/dist/sweetalert2.min.js') }}"></script>

    <!-- Fileinput -->
    <script src="{{ asset('bootstrap-fileinput-4/js/fileinput.js') }}"></script>
    <script src="{{ asset('bootstrap-fileinput-4/js/plugins/piexif.js') }}"></script>
    <script src="{{ asset('bootstrap-fileinput-4/js/plugins/purify.js') }}"></script>


</head>

<body class="nav-md">

<div class="container body" >
    <div class="main_container" >
        <!-- Side Bar Navigation -->
    @include('AdminPanel.templates.sidebar')
            <!-- Top Navigation Bar -->
        @include('AdminPanel.templates.navbar')
        <!-- Body Content -->
        @yield('content')
        <!-- Footer -->
        @include('AdminPanel.templates.footer')
    </div>
</div>


<!-- Custom Theme Scripts -->
<script src="{{ asset('gentelella-1.4.0/build/js/custom.min.js') }}"></script>
</body>
</html>

resources/views/AdminPanel/templates/navbar.blade.php
<!-- top navigation -->
<div class="top_nav" id="notification_app">
    <div class="nav_menu" >
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="#" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        {{ Auth::user()->Firstname }}, {{ Auth::user()->Lastname }}

                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ route('sysadmin.profile.index') }}"> Profile</a></li>
                        <li><a href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit(); "><i class="fa fa-sign-out pull-right"></i> Log Out</a>
                            <form id="logout-form" action="{{ route('sysadmin.logout') }}" method="POST" style="display: none;">
                                @csrf
                                @method('POST')
                            </form>
                        </li>
                    </ul>
                </li>
                {{-- Notification--}}
                <notification-component
                :user="{{ auth()->user() }}" :usernotification="{{ auth()->user()->notifications }}"
                ></notification-component>


            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->

resources/views/AdminPanel/templates/plain-page.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')

    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Plain Page</h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Plain Page</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><a href="#">Settings 1</a>
                                        </li>
                                        <li><a href="#">Settings 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a class="close-link"><i class="fa fa-close"></i></a>
                                </li>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            Add content to the page ...
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->
@endsection

resources/views/AdminPanel/templates/sidebar.blade.php
<div class="col-md-3 left_col">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href=" {{ route('sysadmin.dashboards') }}" class="site_title"><i class="fa fa-paw"></i> <span>eVote System</span></a>
        </div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                @if(Auth::user()->avatar)
                    <img src="{{ Auth::user()->avatar }}" alt="profile_image" class="img-circle profile_img">
                @endif

            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{Auth::user()->Firstname}}, {{ Auth::user()->Lastname }}</h2>
            </div>
            <div class="clearfix"></div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a href="{{ url(route('sysadmin.dashboards')) }}"><i class="fa fa-home"></i> Dashboard</a></li>
                    @can('voters section')
                    <li><a><i class="fa fa-edit"></i> Voter / Student <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @can('add voters')
                            <li><a href="{{ url(route('sysadmin.voters.create')) }}">Register</a></li>
                            @endcan
                           @can('view voters')
                            <li><a href="{{ url(route('sysadmin.voters.index')) }}">Voters / Student List</a></li>
                           @endcan
                        </ul>
                    </li>
                    @endcan
                    @can('candidate section')
                    <li><a><i class="fa fa-users"></i> Candidates <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @can('add candidate')
                            <li><a href="{{ route('sysadmin.candidates.create') }}">Register</a></li>
                            @endcan
                            @can('view candidate')
                            <li><a href="{{ route('sysadmin.candidates.index') }}">Candidates List</a></li>
                            @endcan
                        </ul>
                    </li>
                    @endcan
                    @can('organization section')
                    <li><a><i class="fa fa-table"></i> Organization <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @can('add organization')
                            <li><a href="{{ route('sysadmin.organization.create') }}">Create new Organization</a></li>
                            @endcan
                            @can('view organization')
                            <li><a href="{{ route('sysadmin.organization.index') }}">Organization List</a></li>
                            @endcan
                        </ul>
                    </li>
                    @endcan
                    @can('user section')
                    <li><a><i class="fa fa-user-secret"></i> System User <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @can('add user')
                            <li><a href="{{ route('sysadmin.user.create') }}">Create new user</a></li>
                            @endcan
                            @can('view users')
                            <li><a href="{{ route('sysadmin.user.index') }}">Users list</a></li>
                            @endcan
                        </ul>
                    </li>
                    @endcan
                    @can('system section')
                    <li><a><i class="fa fa-cogs"></i> System Setting <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            @if(auth()->user()->can('configure live monitor') || auth()->user()->can('configure precinct door'))
                            <li><a href="{{ route('sysadmin.general.edit',1) }}">General</a></li>
                            @endif
                            @can('truncate database')
                            <li><a href="{{ route('sysadmin.database.page') }}">Database Setting</a></li>
                            @endcan
                            <li><a href="{{ route('sysadmin.seats.index') }}">Seats</a></li>
                        </ul>
                    </li>
                    @endcan
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings" href="{{ route('sysadmin.general.edit',1) }}">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Profile" href="{{ route('sysadmin.profile.index') }}">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="#" onclick="event.preventDefault(); document.getElementById('logout-form').submit(); ">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                <form id="logout-form" action="{{ route('sysadmin.logout') }}" method="POST" style="display: none;">
                    @csrf
                    @method('POST')
                </form>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>