routes/web.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2020.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Events\ServerMonitor;
use App\Notifications\DoneVoting;
use App\Student;
use App\Traits\SystemInfo;
use App\User;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;

Route::redirect('/','/vote/login');

/*
 *  For System Administrator Auth Path
 */
Route::get('/sysadmin/', 'sysadmin\auth\login@index')->name('sysadmin.login.page');
Route::post('/sysadmin/login','sysadmin\auth\login@logmein')->name('sysadmin.login');
Route::get('/sysadmin/login/success','sysadmin\auth\login@successlogin');
Route::post('/sysadmin/logout','sysadmin\auth\login@logout')->name('sysadmin.logout');

Route::get('/test', function () {
    $user = User::all();
    $student = Student::all();
    //ddd($student[0]);
    Notification::send($user, new DoneVoting($student[0]));
    return 'Event Fired';
});


/*
 *  sysadmin Dashboard
 */
Route::namespace('sysadmin')->prefix('sysadmin')->name('sysadmin.')->middleware(['auth'])->group(function () {
    // System Admin and Developer Admin Dashboard
    Route::get('dashboard', 'Dashboard@index')->name('dashboards');
    // Voters / Student Register & info
    Route::resource('voters', 'voters\voters');
    // Generate Random Password
    Route::get('voters/{id}/generate/random/password', 'voters\voters@GeneratePassword')->name('generateRndPassword');
    // Candidates
    Route::resource('candidates', 'candidates\CandidatesController');
    //users
    Route::resource('account/user', 'account\AccountUserController');
    // Profile
    Route::resource('account/profile', 'profile\Profile');
    //user Activate & Deactivate
    Route::post('account/user/{id}/deactivate', 'account\AccountUserController@Deactivate')->name('user.deactivate');
    Route::post('account/user/{id}/activate', 'account\AccountUserController@Activate')->name('user.activate');
    // Organization
    Route::resource('organization', 'candidates\Organization');
    // General Settings
    Route::resource('settings/general','settings\General');
    // Seats
    Route::get('settings/seats/configuration','settings\SeatsController@index')->name('seats.index');
    Route::put('settings/seats/configuration','settings\SeatsController@update')->name('seats.update');
    // Database Setting
    Route::get('settings/database', 'settings\Database@index')->name('database.page');
    Route::get('settings/database/table/{table}/truncate', 'settings\Database@truncate')->name('database.truncate');
    // Bulk Import Path
    Route::post('voters/bulk/import','voters\voters@import')->name('VotersImport');
    Route::get('voters/bulk/import/file/format','voters\voters@downloadfile')->name('VotersFileFormatImport');

   /*
    *  AJAX Path URL REQUEST
    *
    */
    // system information path
    Route::get('/server/info','sysinfo\info@sysinfo')->name('sysinfopath');

});



/*
 *  For Student Voting Auth Path
 */
Route::get('/vote/login', 'voters\auth\login@index')->name('voters.login.page');
Route::post('/vote/login','voters\auth\login@checklogin')->name('voters.login');
Route::get('/vote/login/success', 'voters\auth\login@successlogin');
Route::post('/vote/logout','voters\auth\login@logout')->name('voters.logout');

/*
 *  Route for student voting dashboard
 * This need to have a auth
 */

Route::namespace('voters')->prefix('precinct')->name('voters.')->middleware(['precinct.door','precinct.voters'])->group(function (){
    Route::get('vote/candidates','vote\CandidatesController@index')->name('dashboards');


    // Semantic API
    Route::post('vote/precinct/candidates', 'vote\VoteController@upVote')->name('voters.vote');

});

Route::view('/vote/close/countdown','partials.vote-is-closed-countdown')->name('countdown.page')->middleware(['precinct.door']);

app/User.php
<?php
/*******************************************************************************
 * @Author MarJose Darang - Copyright (c) 2019.
 *
 * @Licenses GNU GPLv3
 *  https://choosealicense.com/licenses/gpl-3.0/
 *
 ******************************************************************************/

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Role;
use Illuminate\Support\Facades\Auth;
use OwenIt\Auditing\Contracts\Auditable;
use OwenIt\Auditing\Contracts\IpAddressResolver;
use OwenIt\Auditing\Contracts\UserResolver;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements Auditable, UserResolver
{
    use \OwenIt\Auditing\Auditable;
    use Notifiable;
    use HasRoles;



    /**
     * Attributes to include in the Audit.
     *
     * @var array
     */
    protected $auditInclude = [
        'Firstname', 'email', 'Lastname','username','blocked','avatar'
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'Firstname', 'email', 'password','Lastname','username','blocked','avatar'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    /**
     * Resolve the User.
     *
     * @return mixed|null
     */
    public static function resolve()
    {
        return Auth::check() ? Auth::user() : null;
    }
}

resources/views/AdminPanel/users/add-user.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')
    <style>
        .kv-avatar .krajee-default.file-preview-frame,.kv-avatar .krajee-default.file-preview-frame:hover {
            margin: 0;
            padding: 0;
            border: none;
            box-shadow: none;
            text-align: center;
        }
        .kv-avatar {
            display: inline-block;
        }
        .kv-avatar .file-input {
            display: table-cell;
            width: 213px;
        }
        .kv-reqd {
            color: red;
            font-family: monospace;
            font-weight: normal;
        }
    </style>
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="clearfix"></div>
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>Add new System User</h2>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">
                            {{-- Added Validation Error here--}}
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            {{-- /. End of Validation Error here--}}
                            <br />
                            <form method="post" id="createaccount" action="{{ route('sysadmin.user.store') }}" enctype="multipart/form-data"  data-parsley-validate class="form-horizontal form-label-left" >
                                @csrf
                                <div class="row col-lg-12 col-sm-12 text-center">
                                    <div class="text-center">
                                        <div class="kv-avatar">
                                            <div class="file-loading">
                                                <input id="avatar-1" name="userImage" type="file" required>
                                            </div>
                                        </div>
                                        <div class="kv-avatar-hint">
                                            <small>Accepted Image format: jpeg, png, bmp, gif</small>
                                        </div>
                                    </div>
                                </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">First Name <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12" name="First_Name" value="{{ old('First_Name') }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Last Name <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="last-name" name="Last_Name" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('Last_Name')  }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="username">User Name <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="text" id="username" name="username" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('username')  }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="password">Password <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="password" id="password" name="password" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('password')  }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="repassword">Retype Password <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="password" id="repassword" name="password_confirmation" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('password_confirmation')  }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="email">Email <span class="required">*</span>
                                        </label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <input type="email" id="email" name="email" required="required" class="form-control col-md-7 col-xs-12" value="{{ old('email')  }}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Account Role <span class="required">*</span></label>
                                        <div class="col-md-6 col-sm-6 col-xs-12">
                                            <select class="form-control" name="accountrole" required>
                                                @foreach( $roles as $role)
                                                    <option value="{{ $role->id }}">
                                                        {{  $role->role_description }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                            </form>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                                    <button type="submit" form="createaccount" class="btn btn-primary">Save</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /page content -->

    <script>
        $("#avatar-1").fileinput({
            overwriteInitial: true,
            maxFileSize: 1500,
            showClose: false,
            showCaption: false,
            showBrowse: false,
            browseOnZoneClick: true,
            removeLabel: '',
            removeIcon: '<i class="glyphicon glyphicon-remove"></i>',
            removeTitle: 'Cancel or reset changes',
            elErrorContainer: '#kv-avatar-errors-1',
            msgErrorClass: 'alert alert-block alert-danger',
            defaultPreviewContent: '<img src="" alt="Your Avatar"><h6 class="text-muted">Click to select</h6>',
            layoutTemplates: {main2: '{preview} {remove} {browse}'},
            allowedFileExtensions: ["jpg", "png", "gif"]
        });
    </script>

@endsection

resources/views/AdminPanel/users/users.blade.php
@extends('AdminPanel.templates.master_template')

@section('title', 'eVote System')

@section('content')
    <!-- page content -->
    <div class="right_col" role="main">
        <div class="" style="padding-top: 80px;">
            {{-- alert Notification blade--}}
            @include('partials.alerts')
            {{-- /alert Notification blade--}}
        </div>
        <div class="">
            <div class="clearfix"></div>
            <!-- Validation Data Response error-->
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
        @endif
        <!-- Validation Data Response error-->

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <h2>List of Account System User</h2>
                            <ul class="nav navbar-right panel_toolbox">
                                {{-- <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                                 </li>--}}
                                <a href="{{ url(route('sysadmin.user.create')) }}"><i class="fa fa-user-plus fa-2x"></i></a>
                            </ul>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <div class="row">
                                <div class="col-sm-12">
                                    <div class="card-box ">
                                        <table id="" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
                                            <thead>
                                            <tr>
                                                {{--<th><input type="checkbox" id="checkall" class="flat"> Select All</th>--}}
                                                <th>No.</th>
                                                <th>Full Name</th>
                                                <th>Account Name</th>
                                                <th>Email</th>
                                                <th>Account Role</th>
                                                <th>Account Status</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            @foreach($users as $user)
                                                <tr>
                                                    {{-- <td><input type="checkbox" class="flat chck"></td>--}}
                                                    <td>{{ $loop->iteration }}</td>
                                                    <td>{{ $user->Firstname }} {{ $user->Lastname }}</td>
                                                    <td>{{ $user->username }}</td>
                                                    <td>{{ $user->email }}</td>
                                                    <td>{{ $user->roles()->get()->pluck('role_name')->first() }}</td>
                                                    <td>
                                                        @if ($user->blocked === 0)
                                                            Activated
                                                        @else
                                                            Deactivated
                                                        @endif
                                                    </td>
                                                    <td>
                                                        <a href="{{ route('sysadmin.user.edit', $user->id) }}" type="button" class="btn btn-primary btn-round"><i class="fa fa-edit" data-toggle="tooltip" title="Edit user"></i></a>
                                                        <button type="button" class="btn btn-success btn-round" onclick="activate({{ $user->id }})" data-toggle="tooltip" title="Activate user"><i class="fa fa-user fa-check"></i></button>
                                                        <button type="button" class="btn btn-warning btn-round" onclick="deactivate({{ $user->id }})" data-toggle="tooltip" title="Deactivate user"><i class="fa fa-ban"></i></button>
                                                        <button type="button" class="btn btn-danger btn-round" onclick="deleteData( {{ $user->id }})" data-toggle="tooltip" title="Delete user"><i class="fa fa-trash-o"></i></button>
                                                        <form action="{{ route('sysadmin.user.destroy', $user->id) }}" method="POST" id="delete_{{ $user->id }}">
                                                            {{ method_field('DELETE') }}
                                                            @csrf
                                                        </form>
                                                        <form action="{{ route('sysadmin.user.activate', $user->id) }}" method="POST" id="activate_{{ $user->id }}">
                                                            @csrf
                                                        </form>
                                                        <form action="{{ route('sysadmin.user.deactivate', $user->id) }}" method="POST" id="deact_{{ $user->id }}">
                                                            @csrf
                                                        </form>
                                                    </td>
                                                </tr>
                                            @endforeach
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- /page content -->


    <script>
        function deleteData(id){
            const uid = id;
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success btn-round btn-lg',
                    cancelButton: 'btn btn-danger btn-round btn-lg'
                },
                buttonsStyling: false
            });
            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                allowEscapeKey: false,
                allowOutsideClick: false,
                showCancelButton: true,
                confirmButtonText: 'Yes, delete it!',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
            }).then((result) => {
                if (result.value) {
                    //delete that ***
                    $("#delete_"+id).submit();
                }

            })
        }

        function deactivate(id){
            const uid = id;
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success btn-round btn-lg',
                    cancelButton: 'btn btn-danger btn-round btn-lg'
                },
                buttonsStyling: false
            });
            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You want to deactivate/ban this user.",
                type: 'warning',
                allowEscapeKey: false,
                allowOutsideClick: false,
                showCancelButton: true,
                confirmButtonText: 'Yes',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
            }).then((result) => {
                if (result.value) {
                    //ban that ***
                    $("#deact_"+id).submit();
                }

            })
        }
        function activate(id){
            const uid = id;
            const swalWithBootstrapButtons = Swal.mixin({
                customClass: {
                    confirmButton: 'btn btn-success btn-round btn-lg',
                    cancelButton: 'btn btn-danger btn-round btn-lg'
                },
                buttonsStyling: false
            });
            swalWithBootstrapButtons.fire({
                title: 'Are you sure?',
                text: "You want to activate/ removed from being banned to use the system.",
                type: 'question',
                allowEscapeKey: false,
                allowOutsideClick: false,
                showCancelButton: true,
                confirmButtonText: 'Yes',
                cancelButtonText: 'No, cancel!',
                reverseButtons: true,
            }).then((result) => {
                if (result.value) {
                    //activate that ***
                    $("#activate_"+id).submit();
                }

            })
        }

        $(document).ready(function(){

            $(".keytable").DataTable({
                responsive: true,
                keys: !0,
                dom: "Bfrtip",
                buttons: [{
                    extend: "copyHtml5",
                    className: "btn-sm btn-round"
                }, {
                    extend: "csvHtml5",
                    className: "btn-sm btn-round"
                }, {
                    extend: "print",
                    className: "btn-sm btn-round"
                }],
            });
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>

@endsection